# Generated by Django 6.0 on 2026-09-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clause',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='clause',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Expired', 'Expired'), ('Terminated', 'Terminated')], default='Draft', max_length=20),
        ),
    ]
