# Generated by Django 6.0 on 2026-09-07 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_clause_options_clause_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modification',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AddField(
            model_name='modification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='modification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='modification',
            name='clause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='contracts.clause'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
