# Generated by Django 5.2.17 on 2026-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_modification_options_modification_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
