# Generated by Django 5.2.17 on 2026-09-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_modification_approval_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='contracts.version'),
        ),
    ]
